# Generated by Django 4.0.5 on 2022-07-02 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('description1', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('isArchive', models.BooleanField(default=False)),
                ('isTrash', models.BooleanField(default=True)),
                ('isPinned', models.BooleanField(default=False)),
                ('collaborator', models.ManyToManyField(related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(to='labels.labels')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
